### ISSUE TITLE
Implement TimeService JavaScript module

### ISSUE THREAD

**Issue by dryu99** [dryu99/infinite-animal-crossing-lofi#8]
This module is responsible for fetching current time data.

**Notes:**
- The module should supply a single function called `getCurrentHour` that fetches the current time in **24 hours** format
    - e.g. if the current time is 7:00am, the function should return 7
    - e.g. if the current time is 5:30pm, the function should return 17
- The module should contain documentation on the data returned from the function (so other developers using the module know what kind of data to expect)
- A good place to start would be to check out the built-in [JavaScript `Date` class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

**Comment by carmenx** [comment]
we did it :D
